User entity created
PDP-G26/Student_Managment-System pull request #3
Opened 2023-08-03 05:19 UTC by AzimovElyor

2023-08-03 05:20 UTC, AzimovElyor commented
user entityni yaratdim

2023-08-04 11:05 UTC, AzimovElyor commented
Ustoz yaratib chiqdim ammo menda create metodida responceda 406 status error tashlayabdi

2023-08-05 16:45 UTC, aabdurashidov requested changes

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +@PostMapping(value = "/create")
code ni format qiling

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/studentmanagmentsystems/StudentManagmentSystemsApplication.java
> +
ortiqcha bosh joy kerakmi

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/studentmanagmentsystems/StudentManagmentSystemsApplication.java
>  package uz.pdp.studentmanagmentsystems;
projectni packege ni o'zgartiring. aytmoqchimanku. user package ni ham manashu studentmanagementsystems packageni ichida bo'lishi kere

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/User.java
> +    private String surname;
chroyliroq yozing kodni
```
    @Id
    private UUID id;

    @Column(nullable = false)
    private String name;
```

manashunaqa joy tashlab

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/dto/UserCreatDto.java
> +    private String name;
bu yerda ham o'zgaruvchilardan keyin joy tashlang

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/dto/UserResponseDto.java
> +@Data
importdan keyin joy bo'lishi kere

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +@RequestMapping("/users")
users emas user

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +@JsonAutoDetect(getterVisibility= JsonAutoDetect.Visibility.NONE)
bu annotationni nimaga qoydiz?

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +    @GetMapping("/all")
all kerak emas. uji xozi bu design ishlatilmaydi o'chiring. getMappingni o'zi qolsin

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +@PostMapping(value = "/create")
create mapping kere emas uji. o'chiring. shunchaki postmappingni o'zi qolsin

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +    System.out.println("Request keldi");
soutni o'chiring.

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +    @GetMapping("/user/{id}")
```
@GetMapping("{id}")
```

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
bizga bu annotation nimaga kerak?

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/java/uz/pdp/user/service/UserController.java
> +        Map<String, String> errors = new HashMap<>();
controllerda logika yozmang

2023-08-05 16:45 UTC, aabdurashidov commented on src/main/resources/application.properties
> +
configda joy tashlanmaydi. keyin yml format ishlating

2023-08-05 17:00 UTC, AzimovElyor commented on src/main/java/uz/pdp/user/service/UserController.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Bizga bu annotatsiya exceptionlarni handling qilish uchun kerak ustoz validatorlarda tashlangan exceptionlarni message 
chiqmayabdi keyin bu logika orqali chiqarilar ekan

2023-08-05 17:01 UTC, AzimovElyor commented on src/main/resources/application.properties
> +
Ok yaml formatga ogiraman

2023-08-10 09:10 UTC, aabdurashidov approved these changes

2023-08-10 11:08 UTC, merged

2023-08-10 11:08 UTC, AzimovElyor commented
Merge pul request